# Generated by Django 3.1.5 on 2021-01-16 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culinary_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('category_name',)},
        ),
    ]
