# Generated by Django 3.1.5 on 2021-01-16 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('culinary_blog', '0002_auto_20210116_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='culinarypost',
            name='culinary_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categoryName', to='culinary_blog.category'),
            preserve_default=False,
        ),
    ]
