# Generated by Django 3.1.5 on 2021-01-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culinary_blog', '0004_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
