# Generated by Django 3.1.5 on 2021-01-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culinary_blog', '0008_auto_20210123_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culinarypost',
            name='photo',
            field=models.ImageField(blank=True, upload_to='blog_photo/'),
        ),
    ]
