# Generated by Django 3.1.5 on 2021-01-24 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('culinary_blog', '0009_auto_20210123_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culinarypost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='culinary_post', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='culinarypost',
            name='body',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='culinarypost',
            name='culinary_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoryName', to='culinary_blog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='culinarypost',
            name='photo',
            field=models.ImageField(blank=True, upload_to='blog_photo/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='culinarypost',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='culinarypost',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Заголовок'),
        ),
    ]
